### ISSUE TITLE
加油

### ISSUE THREAD

**Issue by DCMMC** [grdaimap/grdaimap#1]
看样子作者是想做一个类似于 Tensorflow 的张量计算库而不是在复杂网络处理上.

Tensorflow 可以理解为 numpy 的一个使用 GPU, 面向占位符(Placeholder)的高性能数值(张量)计算库, 所以我个人认为如果在没有什么基础的情况下要完成一个功能上类似于 Tensorflow 的简化版, 可以按照这样的路程走下去:

* 学习 ML/DL 的基础内容和数学工具, 了解其中的思想, 包括但不限于 `概率论(了解现在的主流 
DL 是如何衡量误差的, e.g. 交叉熵, 以及各种分布)`, `矩阵运算(计算工具)`, `MLP(神经网络的结构)` 以及 `反向传播优化(i.e., 复合函数的链式法则)和各种其他优化算法`, etc.
* 了解如何用软件甚至 GPU 实现矩阵/张量的数值计算的库, 推荐直接从基于 `numpy` 开始
* 参考几个别人实现好的项目, e.g. [ML-From-Scratch](https://github.com/eriklindernoren/ML-From-Scratch), [NumpyDL](https://github.com/oujago/NumpyDL)

**最后, 祝作者加油**

> 关注本项目有段时间了, 也是校友+网友, 正好我也学了点有关的东西, 就希望能够说下自己的想法. 希望作者保持热情, 边学边实践, 把本项目做下去.

P.S. 如果是复杂网络分析处理的库的话, 可以参考 [NetworkX](https://networkx.github.io/) 和 [SNAP](https://snap.stanford.edu/snap/)

**Comment by grdaimap** [comment]
> 看样子作者是想做一个类似于 Tensorflow 的张量计算库而不是在复杂网络处理上.
> 
> Tensorflow 可以理解为 numpy 的一个使用 GPU, 面向占位符(Placeholder)的高性能数值(张量)计算库, 所以我个人认为如果在没有什么基础的情况下要完成一个功能上类似于 Tensorflow 的简化版, 可以按照这样的路程走下去:
> 
> * 学习 ML/DL 的基础内容和数学工具, 了解其中的思想, 包括但不限于 `概率论(了解现在的主流  DL 是如何衡量误差的, e.g. 交叉熵, 以及各种分布)`, `矩阵运算(计算工具)`, `MLP(神经网络的结构)` 以及 `反向传播优化(i.e., 复合函数的链式法则)和各种其他优化算法`, etc.
> * 了解如何用软件甚至 GPU 实现矩阵/张量的数值计算的库, 推荐直接从基于 `numpy` 开始
> * 参考几个别人实现好的项目, e.g. [ML-From-Scratch](https://github.com/eriklindernoren/ML-From-Scratch), [NumpyDL](https://github.com/oujago/NumpyDL)
> 
> **最后, 祝作者加油**
> 
> > 关注本项目有段时间了, 也是校友+网友, 正好我也学了点有关的东西, 就希望能够说下自己的想法. 希望作者保持热情, 边学边实践, 把本项目做下去.
> 
> P.S. 如果是复杂网络分析处理的库的话, 可以参考 [NetworkX](https://networkx.github.io/) 和 [SNAP](https://snap.stanford.edu/snap/)

谢谢大佬，我不会放弃这个项目的 :  )
